# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(613, 417)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitterMain = QtWidgets.QSplitter(self.centralWidget)
        self.splitterMain.setOrientation(QtCore.Qt.Horizontal)
        self.splitterMain.setObjectName("splitterMain")
        self.groupBox = QtWidgets.QGroupBox(self.splitterMain)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btnClearContents = QtWidgets.QPushButton(self.groupBox)
        self.btnClearContents.setObjectName("btnClearContents")
        self.gridLayout.addWidget(self.btnClearContents, 4, 1, 1, 1)
        self.btnIniData = QtWidgets.QPushButton(self.groupBox)
        self.btnIniData.setObjectName("btnIniData")
        self.gridLayout.addWidget(self.btnIniData, 2, 0, 1, 2)
        self.btnAppendRow = QtWidgets.QPushButton(self.groupBox)
        self.btnAppendRow.setObjectName("btnAppendRow")
        self.gridLayout.addWidget(self.btnAppendRow, 3, 1, 1, 1)
        self.btnAutoHeight = QtWidgets.QPushButton(self.groupBox)
        self.btnAutoHeight.setObjectName("btnAutoHeight")
        self.gridLayout.addWidget(self.btnAutoHeight, 5, 0, 1, 1)
        self.btnSetHeader = QtWidgets.QPushButton(self.groupBox)
        self.btnSetHeader.setObjectName("btnSetHeader")
        self.gridLayout.addWidget(self.btnSetHeader, 0, 0, 1, 2)
        self.btnDelCurRow = QtWidgets.QPushButton(self.groupBox)
        self.btnDelCurRow.setObjectName("btnDelCurRow")
        self.gridLayout.addWidget(self.btnDelCurRow, 4, 0, 1, 1)
        self.spinRowCount = QtWidgets.QSpinBox(self.groupBox)
        self.spinRowCount.setObjectName("spinRowCount")
        self.gridLayout.addWidget(self.spinRowCount, 1, 1, 1, 1)
        self.btnInsertRow = QtWidgets.QPushButton(self.groupBox)
        self.btnInsertRow.setObjectName("btnInsertRow")
        self.gridLayout.addWidget(self.btnInsertRow, 3, 0, 1, 1)
        self.btnSetRows = QtWidgets.QPushButton(self.groupBox)
        self.btnSetRows.setObjectName("btnSetRows")
        self.gridLayout.addWidget(self.btnSetRows, 1, 0, 1, 1)
        self.chkBoxRowColor = QtWidgets.QCheckBox(self.groupBox)
        self.chkBoxRowColor.setObjectName("chkBoxRowColor")
        self.gridLayout.addWidget(self.chkBoxRowColor, 7, 1, 1, 1)
        self.chkBoxHeaderH = QtWidgets.QCheckBox(self.groupBox)
        self.chkBoxHeaderH.setObjectName("chkBoxHeaderH")
        self.gridLayout.addWidget(self.chkBoxHeaderH, 8, 0, 1, 1)
        self.btnAutoWidth = QtWidgets.QPushButton(self.groupBox)
        self.btnAutoWidth.setObjectName("btnAutoWidth")
        self.gridLayout.addWidget(self.btnAutoWidth, 5, 1, 1, 1)
        self.chkBoxEditable = QtWidgets.QCheckBox(self.groupBox)
        self.chkBoxEditable.setObjectName("chkBoxEditable")
        self.gridLayout.addWidget(self.chkBoxEditable, 7, 0, 1, 1)
        self.chkBoxHeaderV = QtWidgets.QCheckBox(self.groupBox)
        self.chkBoxHeaderV.setObjectName("chkBoxHeaderV")
        self.gridLayout.addWidget(self.chkBoxHeaderV, 8, 1, 1, 1)
        self.btnReadToText = QtWidgets.QPushButton(self.groupBox)
        self.btnReadToText.setObjectName("btnReadToText")
        self.gridLayout.addWidget(self.btnReadToText, 6, 0, 1, 2)
        self.radioSelectItem_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioSelectItem_2.setObjectName("radioSelectItem_2")
        self.gridLayout.addWidget(self.radioSelectItem_2, 9, 0, 1, 1)
        self.radioSelectItem = QtWidgets.QRadioButton(self.groupBox)
        self.radioSelectItem.setObjectName("radioSelectItem")
        self.gridLayout.addWidget(self.radioSelectItem, 9, 1, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.splitterMain)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableInfo = QtWidgets.QTableWidget(self.splitter)
        self.tableInfo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableInfo.setLineWidth(1)
        self.tableInfo.setMidLineWidth(0)
        self.tableInfo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableInfo.setAutoScrollMargin(16)
        self.tableInfo.setRowCount(5)
        self.tableInfo.setColumnCount(4)
        self.tableInfo.setObjectName("tableInfo")
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setItem(0, 2, item)
        self.textEdit = QtWidgets.QPlainTextEdit(self.splitter)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.splitterMain)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnClearContents.setText(_translate("MainWindow", "清空表格内容"))
        self.btnIniData.setText(_translate("MainWindow", "初始化表格数据"))
        self.btnAppendRow.setText(_translate("MainWindow", "添加行"))
        self.btnAutoHeight.setText(_translate("MainWindow", "自动调节行高"))
        self.btnSetHeader.setText(_translate("MainWindow", "设置表头"))
        self.btnDelCurRow.setText(_translate("MainWindow", "删除当前行"))
        self.btnInsertRow.setText(_translate("MainWindow", "插入行"))
        self.btnSetRows.setText(_translate("MainWindow", "设置行数"))
        self.chkBoxRowColor.setText(_translate("MainWindow", "间隔行底色"))
        self.chkBoxHeaderH.setText(_translate("MainWindow", "显示行表头"))
        self.btnAutoWidth.setText(_translate("MainWindow", "自动调节列宽"))
        self.chkBoxEditable.setText(_translate("MainWindow", "表格可编辑"))
        self.chkBoxHeaderV.setText(_translate("MainWindow", "显示列表头"))
        self.btnReadToText.setText(_translate("MainWindow", "读取表格内容到文本"))
        self.radioSelectItem_2.setText(_translate("MainWindow", "行选择"))
        self.radioSelectItem.setText(_translate("MainWindow", "单元格选择"))
        item = self.tableInfo.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableInfo.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "列1"))
        item = self.tableInfo.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "列2"))
        item = self.tableInfo.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "列3"))
        __sortingEnabled = self.tableInfo.isSortingEnabled()
        self.tableInfo.setSortingEnabled(False)
        item = self.tableInfo.item(0, 0)
        item.setText(_translate("MainWindow", "0行，0列"))
        self.tableInfo.setSortingEnabled(__sortingEnabled)
