# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(641, 273)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Widget)
        self.groupBox.setMinimumSize(QtCore.QSize(360, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnGetTime = QtWidgets.QPushButton(self.groupBox)
        self.btnGetTime.setMinimumSize(QtCore.QSize(130, 0))
        self.btnGetTime.setObjectName("btnGetTime")
        self.horizontalLayout_2.addWidget(self.btnGetTime)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(143, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(48, 0))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox)
        self.timeEdit.setMinimumSize(QtCore.QSize(130, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_2.addWidget(self.timeEdit, 0, 1, 1, 1)
        self.editTime = QtWidgets.QLineEdit(self.groupBox)
        self.editTime.setObjectName("editTime")
        self.gridLayout_2.addWidget(self.editTime, 0, 2, 1, 1)
        self.btnSetTime = QtWidgets.QPushButton(self.groupBox)
        self.btnSetTime.setObjectName("btnSetTime")
        self.gridLayout_2.addWidget(self.btnSetTime, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(48, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.editDate = QtWidgets.QLineEdit(self.groupBox)
        self.editDate.setObjectName("editDate")
        self.gridLayout.addWidget(self.editDate, 0, 2, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setMinimumSize(QtCore.QSize(130, 0))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 3, 25), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 1, 1, 1)
        self.btnSetDate = QtWidgets.QPushButton(self.groupBox)
        self.btnSetDate.setObjectName("btnSetDate")
        self.gridLayout.addWidget(self.btnSetDate, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.editDateTime = QtWidgets.QLineEdit(self.groupBox)
        self.editDateTime.setObjectName("editDateTime")
        self.gridLayout_3.addWidget(self.editDateTime, 0, 2, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(130, 0))
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 3, 25), QtCore.QTime(15, 0, 0)))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_3.addWidget(self.dateTimeEdit, 0, 1, 1, 1)
        self.btnSetDateTime = QtWidgets.QPushButton(self.groupBox)
        self.btnSetDateTime.setObjectName("btnSetDateTime")
        self.gridLayout_3.addWidget(self.btnSetDateTime, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.editCalendar = QtWidgets.QLineEdit(self.groupBox_2)
        self.editCalendar.setObjectName("editCalendar")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editCalendar)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox_2)
        self.calendarWidget.setObjectName("calendarWidget")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.calendarWidget)
        self.horizontalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.groupBox.setTitle(_translate("Widget", "日期时间"))
        self.btnGetTime.setText(_translate("Widget", "读取当前日期时间"))
        self.label_3.setText(_translate("Widget", "字符串显示"))
        self.label.setText(_translate("Widget", "时间"))
        self.editTime.setInputMask(_translate("Widget", "99:99:99;_"))
        self.editTime.setText(_translate("Widget", "::"))
        self.btnSetTime.setText(_translate("Widget", "设置时间"))
        self.label_4.setText(_translate("Widget", "日期"))
        self.editDate.setInputMask(_translate("Widget", "9999-99-99"))
        self.btnSetDate.setText(_translate("Widget", "设置日期"))
        self.label_5.setText(_translate("Widget", "日期时间"))
        self.editDateTime.setInputMask(_translate("Widget", "9999-99-99 99:99:99"))
        self.dateTimeEdit.setDisplayFormat(_translate("Widget", "yyyy-M-d HH:mm:mm"))
        self.btnSetDateTime.setText(_translate("Widget", "设置日期时间"))
        self.groupBox_2.setTitle(_translate("Widget", "日历选择"))
        self.label_2.setText(_translate("Widget", "选择的日期"))
