# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 500)
        MainWindow.setMinimumSize(QtCore.QSize(640, 500))
        MainWindow.setMaximumSize(QtCore.QSize(643, 500))
        MainWindow.setBaseSize(QtCore.QSize(640, 500))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.toolBox = QtWidgets.QToolBox(self.splitter)
        self.toolBox.setMinimumSize(QtCore.QSize(150, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 150, 297))
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnList_Ini = QtWidgets.QToolButton(self.page)
        self.btnList_Ini.setMinimumSize(QtCore.QSize(100, 20))
        self.btnList_Ini.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnList_Ini.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnList_Ini.setObjectName("btnList_Ini")
        self.verticalLayout.addWidget(self.btnList_Ini)
        self.btnList_Clear = QtWidgets.QToolButton(self.page)
        self.btnList_Clear.setMinimumSize(QtCore.QSize(100, 20))
        self.btnList_Clear.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnList_Clear.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnList_Clear.setObjectName("btnList_Clear")
        self.verticalLayout.addWidget(self.btnList_Clear)
        self.btnList_Insert = QtWidgets.QToolButton(self.page)
        self.btnList_Insert.setMinimumSize(QtCore.QSize(100, 20))
        self.btnList_Insert.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnList_Insert.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnList_Insert.setObjectName("btnList_Insert")
        self.verticalLayout.addWidget(self.btnList_Insert)
        self.btnList_Append = QtWidgets.QToolButton(self.page)
        self.btnList_Append.setMinimumSize(QtCore.QSize(100, 20))
        self.btnList_Append.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnList_Append.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnList_Append.setObjectName("btnList_Append")
        self.verticalLayout.addWidget(self.btnList_Append)
        self.btnList_Delete = QtWidgets.QToolButton(self.page)
        self.btnList_Delete.setMinimumSize(QtCore.QSize(100, 20))
        self.btnList_Delete.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnList_Delete.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnList_Delete.setObjectName("btnList_Delete")
        self.verticalLayout.addWidget(self.btnList_Delete)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/408.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 150, 297))
        self.page_2.setObjectName("page_2")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/410.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_2, icon1, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 150, 297))
        self.page_3.setObjectName("page_3")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/412.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_3, icon2, "")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setMinimumSize(QtCore.QSize(470, 400))
        self.tabWidget.setMaximumSize(QtCore.QSize(470, 400))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.frame = QtWidgets.QFrame(self.tab_1)
        self.frame.setGeometry(QtCore.QRect(10, 10, 431, 361))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 411, 40))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.editCurItemText = QtWidgets.QLineEdit(self.groupBox)
        self.editCurItemText.setObjectName("editCurItemText")
        self.horizontalLayout.addWidget(self.editCurItemText)
        self.chkBoxList_Editable = QtWidgets.QCheckBox(self.groupBox)
        self.chkBoxList_Editable.setChecked(True)
        self.chkBoxList_Editable.setObjectName("chkBoxList_Editable")
        self.horizontalLayout.addWidget(self.chkBoxList_Editable)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 60, 411, 51))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSelectItem = QtWidgets.QToolButton(self.groupBox_2)
        self.btnSelectItem.setMinimumSize(QtCore.QSize(100, 25))
        self.btnSelectItem.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btnSelectItem.setAutoRaise(False)
        self.btnSelectItem.setObjectName("btnSelectItem")
        self.horizontalLayout_2.addWidget(self.btnSelectItem)
        self.btnSel_ALL = QtWidgets.QToolButton(self.groupBox_2)
        self.btnSel_ALL.setMinimumSize(QtCore.QSize(85, 25))
        self.btnSel_ALL.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnSel_ALL.setObjectName("btnSel_ALL")
        self.horizontalLayout_2.addWidget(self.btnSel_ALL)
        self.btnSel_None = QtWidgets.QToolButton(self.groupBox_2)
        self.btnSel_None.setMinimumSize(QtCore.QSize(85, 25))
        self.btnSel_None.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnSel_None.setObjectName("btnSel_None")
        self.horizontalLayout_2.addWidget(self.btnSel_None)
        self.btnSel_Invs = QtWidgets.QToolButton(self.groupBox_2)
        self.btnSel_Invs.setMinimumSize(QtCore.QSize(85, 25))
        self.btnSel_Invs.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnSel_Invs.setObjectName("btnSel_Invs")
        self.horizontalLayout_2.addWidget(self.btnSel_Invs)
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(10, 120, 411, 231))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        MainWindow.insertToolBarBreak(self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actList_Append = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/316.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actList_Append.setIcon(icon3)
        self.actList_Append.setObjectName("actList_Append")
        self.actList_Ini = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/128.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actList_Ini.setIcon(icon4)
        self.actList_Ini.setObjectName("actList_Ini")
        self.actList_Clear = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/delete1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actList_Clear.setIcon(icon5)
        self.actList_Clear.setObjectName("actList_Clear")
        self.actList_Insert = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/424.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actList_Insert.setIcon(icon6)
        self.actList_Insert.setObjectName("actList_Insert")
        self.actList_Delete = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/324.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actList_Delete.setIcon(icon7)
        self.actList_Delete.setObjectName("actList_Delete")
        self.actSel_All = QtWidgets.QAction(MainWindow)
        self.actSel_All.setObjectName("actSel_All")
        self.actSel_None = QtWidgets.QAction(MainWindow)
        self.actSel_None.setObjectName("actSel_None")
        self.actSel_Invs = QtWidgets.QAction(MainWindow)
        self.actSel_Invs.setObjectName("actSel_Invs")
        self.actQuit = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/exit.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actQuit.setIcon(icon8)
        self.actQuit.setObjectName("actQuit")
        self.actSelPopMenu = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/516.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSelPopMenu.setIcon(icon9)
        self.actSelPopMenu.setObjectName("actSelPopMenu")
        self.mainToolBar.addAction(self.actList_Ini)
        self.mainToolBar.addAction(self.actList_Clear)
        self.mainToolBar.addAction(self.actList_Insert)
        self.mainToolBar.addAction(self.actList_Append)
        self.mainToolBar.addAction(self.actList_Delete)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actSelPopMenu.triggered.connect(self.actSel_Invs.trigger)
        self.actQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnList_Ini.setText(_translate("MainWindow", "btnList_Ini"))
        self.btnList_Clear.setText(_translate("MainWindow", "btnList_Clear"))
        self.btnList_Insert.setText(_translate("MainWindow", "btnList_Insert"))
        self.btnList_Append.setText(_translate("MainWindow", "btnList_Append"))
        self.btnList_Delete.setText(_translate("MainWindow", "btnList_Delete"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "QListWidget操作"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "QTreeWidget[空]"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "QTableWidget[空]"))
        self.label.setText(_translate("MainWindow", "当前项变化"))
        self.chkBoxList_Editable.setText(_translate("MainWindow", "可编辑"))
        self.btnSelectItem.setText(_translate("MainWindow", "btnSelectItem"))
        self.btnSel_ALL.setText(_translate("MainWindow", "btnSel_ALL"))
        self.btnSel_None.setText(_translate("MainWindow", "btnSel_None"))
        self.btnSel_Invs.setText(_translate("MainWindow", "btnSel_Invs"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "New Item2"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "QListWidget"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "QTreeWidget[空]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "QTableWidget[空]"))
        self.actList_Append.setText(_translate("MainWindow", "添加项"))
        self.actList_Append.setToolTip(_translate("MainWindow", "添加项"))
        self.actList_Append.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actList_Ini.setText(_translate("MainWindow", "初始化列表"))
        self.actList_Ini.setToolTip(_translate("MainWindow", "初始化列表"))
        self.actList_Ini.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actList_Clear.setText(_translate("MainWindow", "清除列表"))
        self.actList_Insert.setText(_translate("MainWindow", "插入项"))
        self.actList_Insert.setToolTip(_translate("MainWindow", "插入项"))
        self.actList_Insert.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actList_Delete.setText(_translate("MainWindow", "删除当前项"))
        self.actList_Delete.setToolTip(_translate("MainWindow", "删除当前项"))
        self.actList_Delete.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actSel_All.setText(_translate("MainWindow", "全选"))
        self.actSel_All.setToolTip(_translate("MainWindow", "全选"))
        self.actSel_None.setText(_translate("MainWindow", "全不选"))
        self.actSel_None.setToolTip(_translate("MainWindow", "全不选"))
        self.actSel_Invs.setText(_translate("MainWindow", "反选"))
        self.actSel_Invs.setToolTip(_translate("MainWindow", "反选"))
        self.actQuit.setText(_translate("MainWindow", "退出"))
        self.actQuit.setToolTip(_translate("MainWindow", "退出程序"))
        self.actSelPopMenu.setText(_translate("MainWindow", "项选项"))
        self.actSelPopMenu.setToolTip(_translate("MainWindow", "项选项"))
import res_rc
