# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(378, 237)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Widget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(66, 33))
        self.label.setMaximumSize(QtCore.QSize(66, 33))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.slider = QtWidgets.QSlider(self.groupBox)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.horizontalLayout.addWidget(self.slider)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(66, 33))
        self.label_2.setMaximumSize(QtCore.QSize(66, 33))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.scrollBar = QtWidgets.QScrollBar(self.groupBox)
        self.scrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar.setObjectName("scrollBar")
        self.horizontalLayout_2.addWidget(self.scrollBar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(66, 33))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.chkBox_Visible = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkBox_Visible.setObjectName("chkBox_Visible")
        self.gridLayout.addWidget(self.chkBox_Visible, 0, 0, 1, 1)
        self.chkBox_Inverted = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkBox_Inverted.setObjectName("chkBox_Inverted")
        self.gridLayout.addWidget(self.chkBox_Inverted, 0, 1, 1, 1)
        self.radio_percent = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_percent.setObjectName("radio_percent")
        self.gridLayout.addWidget(self.radio_percent, 1, 0, 1, 1)
        self.radio_Value = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_Value.setObjectName("radio_Value")
        self.gridLayout.addWidget(self.radio_Value, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label.setText(_translate("Widget", "Slider"))
        self.label_2.setText(_translate("Widget", "ScrollBar"))
        self.label_3.setText(_translate("Widget", "ProgressBar"))
        self.groupBox_2.setTitle(_translate("Widget", "ProgressBar设置"))
        self.chkBox_Visible.setText(_translate("Widget", "textVisible"))
        self.chkBox_Inverted.setText(_translate("Widget", "InvertedAppearance"))
        self.radio_percent.setText(_translate("Widget", "显示格式-百分比"))
        self.radio_Value.setText(_translate("Widget", "显示格式-当前值"))
