# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(397, 213)
        self.verticalLayout = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAlign_Left = QtWidgets.QPushButton(self.frame)
        self.btnAlign_Left.setCheckable(True)
        self.btnAlign_Left.setAutoExclusive(True)
        self.btnAlign_Left.setFlat(True)
        self.btnAlign_Left.setObjectName("btnAlign_Left")
        self.horizontalLayout.addWidget(self.btnAlign_Left)
        self.btnAlign_Center = QtWidgets.QPushButton(self.frame)
        self.btnAlign_Center.setCheckable(True)
        self.btnAlign_Center.setAutoExclusive(True)
        self.btnAlign_Center.setFlat(True)
        self.btnAlign_Center.setObjectName("btnAlign_Center")
        self.horizontalLayout.addWidget(self.btnAlign_Center)
        self.btnAlign_Right = QtWidgets.QPushButton(self.frame)
        self.btnAlign_Right.setCheckable(True)
        self.btnAlign_Right.setAutoExclusive(True)
        self.btnAlign_Right.setFlat(True)
        self.btnAlign_Right.setObjectName("btnAlign_Right")
        self.horizontalLayout.addWidget(self.btnAlign_Right)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnFont_Bold = QtWidgets.QPushButton(self.frame)
        self.btnFont_Bold.setCheckable(True)
        self.btnFont_Bold.setAutoExclusive(True)
        self.btnFont_Bold.setObjectName("btnFont_Bold")
        self.horizontalLayout_2.addWidget(self.btnFont_Bold)
        self.btnFont_Italic = QtWidgets.QPushButton(self.frame)
        self.btnFont_Italic.setCheckable(True)
        self.btnFont_Italic.setAutoExclusive(True)
        self.btnFont_Italic.setObjectName("btnFont_Italic")
        self.horizontalLayout_2.addWidget(self.btnFont_Italic)
        self.btnFont_UnderLine = QtWidgets.QPushButton(self.frame)
        self.btnFont_UnderLine.setCheckable(True)
        self.btnFont_UnderLine.setAutoExclusive(True)
        self.btnFont_UnderLine.setObjectName("btnFont_UnderLine")
        self.horizontalLayout_2.addWidget(self.btnFont_UnderLine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(50)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chkBox_Readonly = QtWidgets.QCheckBox(self.frame)
        self.chkBox_Readonly.setObjectName("chkBox_Readonly")
        self.horizontalLayout_3.addWidget(self.chkBox_Readonly)
        self.chkBox_Enable = QtWidgets.QCheckBox(self.frame)
        self.chkBox_Enable.setObjectName("chkBox_Enable")
        self.horizontalLayout_3.addWidget(self.chkBox_Enable)
        self.chkBox__ClearButton = QtWidgets.QCheckBox(self.frame)
        self.chkBox__ClearButton.setObjectName("chkBox__ClearButton")
        self.horizontalLayout_3.addWidget(self.chkBox__ClearButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.editInput = QtWidgets.QTextBrowser(self.frame)
        self.editInput.setLineWidth(1)
        self.editInput.setMidLineWidth(0)
        self.editInput.setObjectName("editInput")
        self.verticalLayout_2.addWidget(self.editInput)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.btnAlign_Left.setText(_translate("Widget", "居左"))
        self.btnAlign_Center.setText(_translate("Widget", "居中"))
        self.btnAlign_Right.setText(_translate("Widget", "居右"))
        self.btnFont_Bold.setText(_translate("Widget", "粗体"))
        self.btnFont_Italic.setText(_translate("Widget", "斜体"))
        self.btnFont_UnderLine.setText(_translate("Widget", "下划线"))
        self.chkBox_Readonly.setText(_translate("Widget", "Readonly"))
        self.chkBox_Enable.setText(_translate("Widget", "Enabled"))
        self.chkBox__ClearButton.setText(_translate("Widget", "ClearBurronEnabled"))
        self.editInput.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">显示测试文本</span></p></body></html>"))
