# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 393)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setGeometry(QtCore.QRect(9, 9, 631, 311))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtWidgets.QTableView(self.groupBox)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actOpenFile = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/open.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actOpenFile.setIcon(icon)
        self.actOpenFile.setObjectName("actOpenFile")
        self.actSaveFile = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/save.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSaveFile.setIcon(icon1)
        self.actSaveFile.setObjectName("actSaveFile")
        self.actModelData = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/export1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actModelData.setIcon(icon2)
        self.actModelData.setObjectName("actModelData")
        self.actAppend = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/append.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actAppend.setIcon(icon3)
        self.actAppend.setObjectName("actAppend")
        self.actInsert = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/306.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actInsert.setIcon(icon4)
        self.actInsert.setObjectName("actInsert")
        self.actDel = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/delete.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actDel.setIcon(icon5)
        self.actDel.setObjectName("actDel")
        self.actAlignLeft = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/508.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actAlignLeft.setIcon(icon6)
        self.actAlignLeft.setObjectName("actAlignLeft")
        self.actAlignCenter = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/510.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actAlignCenter.setIcon(icon7)
        self.actAlignCenter.setObjectName("actAlignCenter")
        self.actAlignRight = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/512.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actAlignRight.setIcon(icon8)
        self.actAlignRight.setObjectName("actAlignRight")
        self.actFontBold = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/500.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actFontBold.setIcon(icon9)
        self.actFontBold.setObjectName("actFontBold")
        self.actExit = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/images/exit.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actExit.setIcon(icon10)
        self.actExit.setObjectName("actExit")
        self.mainToolBar.addAction(self.actOpenFile)
        self.mainToolBar.addAction(self.actSaveFile)
        self.mainToolBar.addAction(self.actModelData)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actAppend)
        self.mainToolBar.addAction(self.actInsert)
        self.mainToolBar.addAction(self.actDel)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actAlignLeft)
        self.mainToolBar.addAction(self.actAlignCenter)
        self.mainToolBar.addAction(self.actAlignRight)
        self.mainToolBar.addAction(self.actFontBold)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actExit)

        self.retranslateUi(MainWindow)
        self.actExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "tableView"))
        self.groupBox_2.setTitle(_translate("MainWindow", "plainTextEdit"))
        self.actOpenFile.setText(_translate("MainWindow", "打开文件"))
        self.actOpenFile.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actSaveFile.setText(_translate("MainWindow", "另存文件"))
        self.actSaveFile.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actModelData.setText(_translate("MainWindow", "模型数据"))
        self.actAppend.setText(_translate("MainWindow", "添加行"))
        self.actInsert.setText(_translate("MainWindow", "插入行"))
        self.actDel.setText(_translate("MainWindow", "删除行"))
        self.actAlignLeft.setText(_translate("MainWindow", "居左"))
        self.actAlignCenter.setText(_translate("MainWindow", "居中"))
        self.actAlignRight.setText(_translate("MainWindow", "居右"))
        self.actFontBold.setText(_translate("MainWindow", "粗体"))
        self.actExit.setText(_translate("MainWindow", "退出"))
import res_rc
