# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 481)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 620, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu_F = QtWidgets.QMenu(self.menuBar)
        self.menu_F.setObjectName("menu_F")
        self.menu_E = QtWidgets.QMenu(self.menuBar)
        self.menu_E.setObjectName("menu_E")
        self.menu_M = QtWidgets.QMenu(self.menuBar)
        self.menu_M.setObjectName("menu_M")
        self.menu = QtWidgets.QMenu(self.menu_M)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainToolBar.setAutoFillBackground(False)
        self.mainToolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.mainToolBar.setOrientation(QtCore.Qt.Horizontal)
        self.mainToolBar.setIconSize(QtCore.QSize(12, 12))
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        MainWindow.insertToolBarBreak(self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actFile_New = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/100.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actFile_New.setIcon(icon)
        self.actFile_New.setObjectName("actFile_New")
        self.actFile_Open = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/122.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actFile_Open.setIcon(icon1)
        self.actFile_Open.setObjectName("actFile_Open")
        self.actFile_Save = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/104.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actFile_Save.setIcon(icon2)
        self.actFile_Save.setObjectName("actFile_Save")
        self.actClose = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actClose.setIcon(icon3)
        self.actClose.setObjectName("actClose")
        self.actEdit_Cut = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/200.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEdit_Cut.setIcon(icon4)
        self.actEdit_Cut.setObjectName("actEdit_Cut")
        self.actEdit_Copy = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/202.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEdit_Copy.setIcon(icon5)
        self.actEdit_Copy.setObjectName("actEdit_Copy")
        self.actEdit_Paste = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/204.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEdit_Paste.setIcon(icon6)
        self.actEdit_Paste.setObjectName("actEdit_Paste")
        self.actEdit_Undo = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/206.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEdit_Undo.setIcon(icon7)
        self.actEdit_Undo.setObjectName("actEdit_Undo")
        self.actEdit_Redo = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/208.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEdit_Redo.setIcon(icon8)
        self.actEdit_Redo.setObjectName("actEdit_Redo")
        self.actEdit_SelectAll = QtWidgets.QAction(MainWindow)
        self.actEdit_SelectAll.setObjectName("actEdit_SelectAll")
        self.actEdit_Clear = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/212.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEdit_Clear.setIcon(icon9)
        self.actEdit_Clear.setObjectName("actEdit_Clear")
        self.actFont_Bold = QtWidgets.QAction(MainWindow)
        self.actFont_Bold.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/images/500.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actFont_Bold.setIcon(icon10)
        self.actFont_Bold.setObjectName("actFont_Bold")
        self.actFont_Italic = QtWidgets.QAction(MainWindow)
        self.actFont_Italic.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/images/502.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actFont_Italic.setIcon(icon11)
        self.actFont_Italic.setObjectName("actFont_Italic")
        self.actFont_UnderLine = QtWidgets.QAction(MainWindow)
        self.actFont_UnderLine.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/images/504.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actFont_UnderLine.setIcon(icon12)
        self.actFont_UnderLine.setObjectName("actFont_UnderLine")
        self.actSys_ToggleText = QtWidgets.QAction(MainWindow)
        self.actSys_ToggleText.setCheckable(True)
        self.actSys_ToggleText.setChecked(True)
        self.actSys_ToggleText.setObjectName("actSys_ToggleText")
        self.actLang_CN = QtWidgets.QAction(MainWindow)
        self.actLang_CN.setCheckable(True)
        self.actLang_CN.setChecked(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/images/CN.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actLang_CN.setIcon(icon13)
        self.actLang_CN.setObjectName("actLang_CN")
        self.actLang_EN = QtWidgets.QAction(MainWindow)
        self.actLang_EN.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/images/timg2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actLang_EN.setIcon(icon14)
        self.actLang_EN.setObjectName("actLang_EN")
        self.menu_F.addAction(self.actFile_New)
        self.menu_F.addAction(self.actFile_Open)
        self.menu_F.addAction(self.actFile_Save)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actClose)
        self.menu_E.addAction(self.actEdit_Cut)
        self.menu_E.addAction(self.actEdit_Copy)
        self.menu_E.addAction(self.actEdit_Paste)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.actEdit_Undo)
        self.menu_E.addAction(self.actEdit_Redo)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.actEdit_SelectAll)
        self.menu_E.addAction(self.actEdit_Clear)
        self.menu.addAction(self.actLang_CN)
        self.menu.addAction(self.actLang_EN)
        self.menu_M.addAction(self.actFont_Bold)
        self.menu_M.addAction(self.actFont_Italic)
        self.menu_M.addAction(self.actFont_UnderLine)
        self.menu_M.addSeparator()
        self.menu_M.addAction(self.actSys_ToggleText)
        self.menu_M.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_F.menuAction())
        self.menuBar.addAction(self.menu_E.menuAction())
        self.menuBar.addAction(self.menu_M.menuAction())
        self.mainToolBar.addAction(self.actFile_New)
        self.mainToolBar.addAction(self.actFile_Open)
        self.mainToolBar.addAction(self.actFile_Save)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actEdit_Cut)
        self.mainToolBar.addAction(self.actEdit_Copy)
        self.mainToolBar.addAction(self.actEdit_Paste)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actEdit_Undo)
        self.mainToolBar.addAction(self.actEdit_Redo)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actFont_Bold)
        self.mainToolBar.addAction(self.actFont_Italic)
        self.mainToolBar.addAction(self.actFont_UnderLine)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actLang_CN)
        self.mainToolBar.addAction(self.actLang_EN)

        self.retranslateUi(MainWindow)
        self.textEdit.undoAvailable['bool'].connect(self.actEdit_Undo.setEnabled)
        self.textEdit.redoAvailable['bool'].connect(self.actEdit_Redo.setEnabled)
        self.actEdit_Undo.triggered.connect(self.textEdit.undo)
        self.actEdit_SelectAll.triggered.connect(self.textEdit.selectAll)
        self.actEdit_Redo.triggered.connect(self.textEdit.redo)
        self.actEdit_Paste.triggered.connect(self.textEdit.paste)
        self.actEdit_Cut.triggered.connect(self.textEdit.cut)
        self.actEdit_Copy.triggered.connect(self.textEdit.copy)
        self.actEdit_Clear.triggered.connect(self.textEdit.clear)
        self.actClose.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_F.setTitle(_translate("MainWindow", "文件(F)"))
        self.menu_E.setTitle(_translate("MainWindow", "编辑(E)"))
        self.menu_M.setTitle(_translate("MainWindow", "格式(M)"))
        self.menu.setTitle(_translate("MainWindow", "界面语音"))
        self.actFile_New.setText(_translate("MainWindow", "新建"))
        self.actFile_New.setToolTip(_translate("MainWindow", "新建文件"))
        self.actFile_New.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actFile_Open.setText(_translate("MainWindow", "打开..."))
        self.actFile_Open.setToolTip(_translate("MainWindow", "打开文件"))
        self.actFile_Open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actFile_Save.setText(_translate("MainWindow", "保存"))
        self.actFile_Save.setToolTip(_translate("MainWindow", "保存修改"))
        self.actFile_Save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actClose.setText(_translate("MainWindow", "关闭"))
        self.actClose.setToolTip(_translate("MainWindow", "关闭本窗口"))
        self.actEdit_Cut.setText(_translate("MainWindow", "剪切"))
        self.actEdit_Cut.setToolTip(_translate("MainWindow", "剪切到粘贴板"))
        self.actEdit_Cut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actEdit_Copy.setText(_translate("MainWindow", "复制"))
        self.actEdit_Copy.setToolTip(_translate("MainWindow", "复制到粘贴板"))
        self.actEdit_Copy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actEdit_Paste.setText(_translate("MainWindow", "粘贴"))
        self.actEdit_Paste.setToolTip(_translate("MainWindow", "从粘贴板粘贴"))
        self.actEdit_Paste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actEdit_Undo.setText(_translate("MainWindow", "撤销"))
        self.actEdit_Undo.setToolTip(_translate("MainWindow", "撤销上一次的操作"))
        self.actEdit_Undo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actEdit_Redo.setText(_translate("MainWindow", "重做"))
        self.actEdit_Redo.setToolTip(_translate("MainWindow", "重做上一次操作"))
        self.actEdit_Redo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actEdit_SelectAll.setText(_translate("MainWindow", "全选"))
        self.actEdit_SelectAll.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actEdit_Clear.setText(_translate("MainWindow", "清空"))
        self.actFont_Bold.setText(_translate("MainWindow", "粗体"))
        self.actFont_Italic.setText(_translate("MainWindow", "斜体"))
        self.actFont_UnderLine.setText(_translate("MainWindow", "下划线"))
        self.actSys_ToggleText.setText(_translate("MainWindow", "显示工具栏文字"))
        self.actSys_ToggleText.setToolTip(_translate("MainWindow", "显示工具栏文字文字"))
        self.actLang_CN.setText(_translate("MainWindow", "汉语"))
        self.actLang_CN.setToolTip(_translate("MainWindow", "汉语界面"))
        self.actLang_EN.setText(_translate("MainWindow", "英语"))
        self.actLang_EN.setToolTip(_translate("MainWindow", "英语界面"))
import res_rc
